= VR Avatar Utilities
:icons: font


A growing collection of utilities that I have created to assist my workflows
working on optimizing and creating custom content for VR avatars in Blender.

Developed against Blender 4.1.1.  May technically be compatible with previous
Blender versions but has not been tested on any.

== Features

This plugin adds new collapsible panels titled "VR Avatar Utils" to the "Data"
tab in the "Armature" and "Mesh" context.

=== Armatures

==== Bone Rotation Mode Normalization

Allows converting the transform rotation mode of all bones in an armature to a
target value without altering the rotation.


=== Meshes

==== Synchronize Shape Keys

Synchronizes the values of shape keys on the current mesh with matching shape
keys on other meshes in the scene or file.


==== Rename Shape Keys

Allows mass renaming of shape keys across all meshes in the scene or file.

== Development

=== Project Structure

The source for the project exists entirely under the `src/` directory.  Under
this directory are the following packages:

`bpy`::
This is a reference package providing type definitions as a stand-in for the
real Blender `bpy` library.  This package does not contain any functional code,
only `Protocol` and `Literal` definitions built on Python's `typing` package
that enable smart editor features such as autocomplete and type based error
checking.
+
The actual `bpy` library available via pip is heavyweight and requires
additional transitive dependencies whereas this reference package only depends
on the Python standard library.
+
The code in this package is *not* included in the addon distribution zip.

`fxcpds_vr_avatar_utils`::
This package contains the implementation of the addon.  This is the only package
that is included in the addon distribution zip.
+
This package has no dependencies outside itself and the Blender `bpy` library.

`mathutils`::
Similar to the included `bpy` package, this is a reference package that provides
type definitions for components of the Blender `mathutils` package. This package
does not contain any functional code.
+
The code in this package is *not* included in the addon distribution zip.

`scripts`::
Miscellaneous scripts that have been used to aid my workflow that are included
for reference or prototyping new addon features.
+
The code in this package is *not* included in the addon distribution zip.

